// <auto-generated />
using Banka;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banka.Migrations
{
    [DbContext(typeof(BankaDbContext))]
    [Migration("20231015131044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Banka.TekuciRacun", b =>
                {
                    b.Property<string>("IBAN")
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<float>("LimitIsplata")
                        .HasColumnType("REAL");

                    b.Property<float>("LimitUplata")
                        .HasColumnType("REAL");

                    b.Property<float>("RaspoloziviIznos")
                        .HasColumnType("REAL");

                    b.Property<float>("RezerviraniIznos")
                        .HasColumnType("REAL");

                    b.Property<float>("StanjeRacuna")
                        .HasColumnType("REAL");

                    b.HasKey("IBAN");

                    b.ToTable("TekuciRacuni");
                });
#pragma warning restore 612, 618
        }
    }
}
